import type { DealerProfitLossData } from "./types";

/** Mock P&L dataset aligned with the client reference design (May 2024). */
export const DEALER_PROFIT_LOSS_MOCK: DealerProfitLossData = {
  period: {
    start: "2024-05-01",
    end: "2024-05-31",
    label: "May 2024",
    columnLabel: "This Month",
    comparisonColumnLabel: "Last Month",
    comparisonLabel: "Apr 2024",
  },
  kpis: {
    totalRevenue: 2_458_750,
    totalRevenueDelta: "�†‘ 18.4% vs Apr 2024",
    grossProfit: 487_350,
    grossProfitDelta: "�†‘ 21.2% vs Apr 2024",
    totalExpenses: 291_580,
    totalExpensesDelta: "�†‘ 11.7% vs Apr 2024",
    netProfit: 195_770,
    netProfitDelta: "�†‘ 35.6% vs Apr 2024",
    grossMargin: 19.8,
    grossMarginDelta: "�†‘ 2.1% vs Apr 2024",
  },
  statementRows: [
    {
      id: "hdr-income",
      kind: "section-header",
      section: "income",
      label: "INCOME",
      thisMonth: null,
      lastMonth: null,
    },
    {
      id: "vehicle-retail",
      kind: "line-item",
      section: "income",
      label: "Vehicle Sales (Retail)",
      thisMonth: 1_850_000,
      lastMonth: 1_562_000,
    },
    {
      id: "wholesale",
      kind: "line-item",
      section: "income",
      label: "Wholesale Sales",
      thisMonth: 508_750,
      lastMonth: 432_500,
    },
    {
      id: "other-income",
      kind: "line-item",
      section: "income",
      label: "Other Income",
      thisMonth: 100_000,
      lastMonth: 88_000,
    },
    {
      id: "total-income",
      kind: "subtotal",
      section: "income",
      label: "TOTAL INCOME",
      thisMonth: 2_458_750,
      lastMonth: 2_082_500,
    },
    {
      id: "hdr-cogs",
      kind: "section-header",
      section: "cogs",
      label: "COST OF GOODS SOLD",
      thisMonth: null,
      lastMonth: null,
    },
    {
      id: "inventory-purchases",
      kind: "line-item",
      section: "cogs",
      label: "Inventory Purchases",
      thisMonth: 1_680_000,
      lastMonth: 1_445_000,
    },
    {
      id: "recon-costs",
      kind: "line-item",
      section: "cogs",
      label: "Reconditioning Costs",
      thisMonth: 291_400,
      lastMonth: 258_200,
    },
    {
      id: "total-cogs",
      kind: "subtotal",
      section: "cogs",
      label: "TOTAL COGS",
      thisMonth: 1_971_400,
      lastMonth: 1_703_200,
    },
    {
      id: "gross-profit",
      kind: "total",
      section: "gross_profit",
      label: "GROSS PROFIT",
      thisMonth: 487_350,
      lastMonth: 379_300,
    },
    {
      id: "gross-margin",
      kind: "metric",
      section: "gross_profit",
      label: "GROSS MARGIN",
      thisMonth: 19.8,
      lastMonth: 18.2,
      isPercent: true,
    },
    {
      id: "hdr-opex",
      kind: "section-header",
      section: "operating_expenses",
      label: "OPERATING EXPENSES",
      thisMonth: null,
      lastMonth: null,
    },
    {
      id: "payroll",
      kind: "line-item",
      section: "operating_expenses",
      label: "Payroll Expenses",
      thisMonth: 92_400,
      lastMonth: 84_200,
    },
    {
      id: "advertising",
      kind: "line-item",
      section: "operating_expenses",
      label: "Advertising",
      thisMonth: 18_750,
      lastMonth: 16_400,
    },
    {
      id: "rent",
      kind: "line-item",
      section: "operating_expenses",
      label: "Rent & Lease",
      thisMonth: 25_000,
      lastMonth: 24_500,
    },
    {
      id: "utilities",
      kind: "line-item",
      section: "operating_expenses",
      label: "Utilities",
      thisMonth: 5_800,
      lastMonth: 5_200,
    },
    {
      id: "office",
      kind: "line-item",
      section: "operating_expenses",
      label: "Office Expenses",
      thisMonth: 6_280,
      lastMonth: 5_900,
    },
    {
      id: "vehicle-exp",
      kind: "line-item",
      section: "operating_expenses",
      label: "Vehicle Expenses",
      thisMonth: 68_900,
      lastMonth: 62_100,
    },
    {
      id: "insurance",
      kind: "line-item",
      section: "operating_expenses",
      label: "Insurance",
      thisMonth: 15_350,
      lastMonth: 14_800,
    },
    {
      id: "professional",
      kind: "line-item",
      section: "operating_expenses",
      label: "Professional Fees",
      thisMonth: 12_400,
      lastMonth: 11_200,
    },
    {
      id: "other-exp",
      kind: "line-item",
      section: "operating_expenses",
      label: "Other Expenses",
      thisMonth: 19_100,
      lastMonth: 17_600,
    },
    {
      id: "total-opex",
      kind: "subtotal",
      section: "operating_expenses",
      label: "TOTAL OPERATING EXPENSES",
      thisMonth: 263_980,
      lastMonth: 241_900,
    },
    {
      id: "net-profit",
      kind: "total",
      section: "net_profit",
      label: "NET PROFIT",
      thisMonth: 195_770,
      lastMonth: 144_400,
    },
    {
      id: "net-margin",
      kind: "metric",
      section: "net_profit",
      label: "NET PROFIT MARGIN",
      thisMonth: 8.0,
      lastMonth: 6.9,
      isPercent: true,
    },
  ],
  monthlyTrend: [
    {
      label: "Dec 2023",
      revenue: 1_820_000,
      grossProfit: 328_000,
      expenses: 198_000,
      netProfit: 130_000,
    },
    {
      label: "Jan 2024",
      revenue: 1_950_000,
      grossProfit: 355_000,
      expenses: 210_500,
      netProfit: 144_500,
    },
    {
      label: "Feb 2024",
      revenue: 2_080_000,
      grossProfit: 382_000,
      expenses: 225_800,
      netProfit: 156_200,
    },
    {
      label: "Mar 2024",
      revenue: 2_150_000,
      grossProfit: 405_000,
      expenses: 238_400,
      netProfit: 166_600,
    },
    {
      label: "Apr 2024",
      revenue: 2_082_500,
      grossProfit: 379_300,
      expenses: 241_900,
      netProfit: 144_400,
    },
    {
      label: "May 2024",
      revenue: 2_458_750,
      grossProfit: 487_350,
      expenses: 291_580,
      netProfit: 195_770,
    },
  ],
  expenseTotal: 251_330,
  expenseSegments: [
    {
      id: "payroll",
      label: "Payroll Expenses",
      amount: 92_400,
      percent: 36.7,
      color: "#3b82f6",
    },
    {
      id: "vehicle",
      label: "Vehicle Expenses",
      amount: 68_900,
      percent: 27.4,
      color: "#f97316",
    },
    {
      id: "rent",
      label: "Rent & Lease",
      amount: 25_000,
      percent: 9.9,
      color: "#eab308",
    },
    {
      id: "advertising",
      label: "Advertising",
      amount: 18_750,
      percent: 7.5,
      color: "#a855f7",
    },
    {
      id: "insurance",
      label: "Insurance",
      amount: 15_350,
      percent: 6.1,
      color: "#ec4899",
    },
    {
      id: "office",
      label: "Office Expenses",
      amount: 6_280,
      percent: 2.5,
      color: "#06b6d4",
    },
    {
      id: "utilities",
      label: "Utilities",
      amount: 5_800,
      percent: 2.3,
      color: "#64748b",
    },
    {
      id: "other",
      label: "Other Expenses",
      amount: 19_100,
      percent: 7.6,
      color: "#94a3b8",
    },
  ],
  topIncomeSources: [
    {
      id: "retail",
      label: "Vehicle Sales (Retail)",
      amount: 1_850_000,
      percentOfTotal: 75.2,
      color: "#3b82f6",
    },
    {
      id: "wholesale",
      label: "Wholesale Sales",
      amount: 508_750,
      percentOfTotal: 20.7,
      color: "#10b981",
    },
    {
      id: "other",
      label: "Other Income",
      amount: 100_000,
      percentOfTotal: 4.1,
      color: "#a855f7",
    },
  ],
  topExpenseCategories: [
    {
      id: "payroll",
      label: "Payroll Expenses",
      amount: 92_400,
      percentOfTotal: 36.7,
      color: "#ef4444",
    },
    {
      id: "vehicle",
      label: "Vehicle Expenses",
      amount: 68_900,
      percentOfTotal: 27.4,
      color: "#f97316",
    },
    {
      id: "rent",
      label: "Rent & Lease",
      amount: 25_000,
      percentOfTotal: 9.9,
      color: "#eab308",
    },
  ],
  timeframeOptions: [
    { value: "this_month", label: "This Month" },
    { value: "last_month", label: "Last Month" },
    { value: "this_quarter", label: "This Quarter" },
    { value: "this_year", label: "This Year" },
    { value: "custom", label: "Custom Range" },
  ],
};
