export const PAYROLL_EMPLOYEES = [
  { payrollId: "payroll-1", empCode: "EMP-1001", name: "Mike Johnson", salesRepId: "SR-001", role: "Sales Representative", avatar: "https://i.pravatar.cc/64?img=12", phone: "(555) 123-4567", email: "mike.j@dealership.com", hireDate: "Jan 15, 2024", payFrequency: "Bi-Weekly" as const },
  { payrollId: "payroll-2", empCode: "EMP-1002", name: "Sarah Williams", salesRepId: "SR-002", role: "Sales Representative", avatar: "https://i.pravatar.cc/64?img=47", phone: "(555) 234-5678", email: "sarah.w@dealership.com", hireDate: "Mar 3, 2023", payFrequency: "Bi-Weekly" as const },
  { payrollId: "payroll-3", empCode: "EMP-1003", name: "Mike Thompson", salesRepId: "SR-003", role: "Sales Representative", avatar: "https://i.pravatar.cc/64?img=33", phone: "(555) 345-6789", email: "mike.t@dealership.com", hireDate: "Jun 12, 2022", payFrequency: "Bi-Weekly" as const },
  { payrollId: "payroll-4", empCode: "EMP-1004", name: "Emily Davis", salesRepId: "SR-004", role: "Sales Representative", avatar: "https://i.pravatar.cc/64?img=45", phone: "(555) 456-7890", email: "emily.d@dealership.com", hireDate: "Aug 20, 2023", payFrequency: "Bi-Weekly" as const },
  { payrollId: "payroll-5", empCode: "EMP-1005", name: "James Wilson", salesRepId: "SR-005", role: "Sales Manager", avatar: "https://i.pravatar.cc/64?img=15", phone: "(555) 567-8901", email: "james.w@dealership.com", hireDate: "Feb 1, 2021", payFrequency: "Bi-Weekly" as const },
  { payrollId: "payroll-6", empCode: "EMP-1006", name: "Lisa Anderson", salesRepId: "SR-006", role: "Sales Representative", avatar: "https://i.pravatar.cc/64?img=32", phone: "(555) 678-9012", email: "lisa.a@dealership.com", hireDate: "Nov 5, 2023", payFrequency: "Bi-Weekly" as const },
  { payrollId: "payroll-7", empCode: "EMP-1007", name: "David Martinez", salesRepId: "SR-007", role: "Sales Representative", avatar: "https://i.pravatar.cc/64?img=52", phone: "(555) 789-0123", email: "david.m@dealership.com", hireDate: "Apr 18, 2024", payFrequency: "Bi-Weekly" as const },
  { payrollId: "payroll-8", empCode: "EMP-1008", name: "Jennifer Lee", salesRepId: "SR-008", role: "Finance Admin", avatar: "https://i.pravatar.cc/64?img=25", phone: "(555) 890-1234", email: "jennifer.l@dealership.com", hireDate: "Sep 9, 2022", payFrequency: "Semi-Monthly" as const },
  { payrollId: "payroll-9", empCode: "EMP-1009", name: "Robert Brown", salesRepId: "SR-009", role: "Sales Representative", avatar: "https://i.pravatar.cc/64?img=68", phone: "(555) 901-2345", email: "robert.b@dealership.com", hireDate: "Jul 22, 2023", payFrequency: "Bi-Weekly" as const },
  { payrollId: "payroll-10", empCode: "EMP-1010", name: "Amanda Taylor", salesRepId: "SR-010", role: "Sales Representative", avatar: "https://i.pravatar.cc/64?img=44", phone: "(555) 012-3456", email: "amanda.t@dealership.com", hireDate: "Dec 1, 2024", payFrequency: "Bi-Weekly" as const },
  { payrollId: "payroll-11", empCode: "EMP-1011", name: "Chris Garcia", salesRepId: "SR-011", role: "Sales Representative", avatar: "https://i.pravatar.cc/64?img=51", phone: "(555) 111-2222", email: "chris.g@dealership.com", hireDate: "May 14, 2023", payFrequency: "Bi-Weekly" as const },
  { payrollId: "payroll-12", empCode: "EMP-1012", name: "Michelle White", salesRepId: "SR-012", role: "Office Manager", avatar: "https://i.pravatar.cc/64?img=29", phone: "(555) 222-3333", email: "michelle.w@dealership.com", hireDate: "Jan 10, 2020", payFrequency: "Semi-Monthly" as const },
  { payrollId: "payroll-13", empCode: "EMP-1013", name: "Kevin Harris", salesRepId: "SR-013", role: "Sales Representative", avatar: "https://i.pravatar.cc/64?img=13", phone: "(555) 333-4444", email: "kevin.h@dealership.com", hireDate: "Oct 30, 2024", payFrequency: "Bi-Weekly" as const },
  { payrollId: "payroll-14", empCode: "EMP-1014", name: "Rachel Clark", salesRepId: "SR-014", role: "Sales Representative", avatar: "https://i.pravatar.cc/64?img=38", phone: "(555) 444-5555", email: "rachel.c@dealership.com", hireDate: "Feb 28, 2023", payFrequency: "Bi-Weekly" as const },
  { payrollId: "payroll-15", empCode: "EMP-1015", name: "Daniel Lewis", salesRepId: "SR-015", role: "Sales Representative", avatar: "https://i.pravatar.cc/64?img=60", phone: "(555) 555-6666", email: "daniel.l@dealership.com", hireDate: "Jun 5, 2022", payFrequency: "Bi-Weekly" as const },
  { payrollId: "payroll-16", empCode: "EMP-1016", name: "Stephanie Hall", salesRepId: "SR-016", role: "Sales Representative", avatar: "https://i.pravatar.cc/64?img=41", phone: "(555) 666-7777", email: "stephanie.h@dealership.com", hireDate: "Mar 17, 2024", payFrequency: "Bi-Weekly" as const },
  { payrollId: "payroll-17", empCode: "EMP-1017", name: "Brian Young", salesRepId: "SR-017", role: "Sales Representative", avatar: "https://i.pravatar.cc/64?img=56", phone: "(555) 777-8888", email: "brian.y@dealership.com", hireDate: "Aug 8, 2023", payFrequency: "Bi-Weekly" as const },
  { payrollId: "payroll-18", empCode: "EMP-1018", name: "Nicole King", salesRepId: "SR-018", role: "Sales Representative", avatar: "https://i.pravatar.cc/64?img=49", phone: "(555) 888-9999", email: "nicole.k@dealership.com", hireDate: "Nov 22, 2024", payFrequency: "Bi-Weekly" as const },
] as const;

export type PayrollEmployeeRecord = (typeof PAYROLL_EMPLOYEES)[number];
