import type { ExpenseDetail, ExpenseStats } from "./types";

type ExpenseDetailSeed = Omit<ExpenseDetail, "expenseKind" | "expenseSubcategory">;

function withExpenseKind(row: ExpenseDetailSeed): ExpenseDetail {
  return {
    ...row,
    expenseKind: row.category === "vehicle" ? "vehicle" : "dealership",
    expenseSubcategory:
      row.category === "vehicle"
        ? (row.title.split(" - ")[0] ?? "Other")
        : null,
  };
}

export const EXPENSE_STATS_MOCK: ExpenseStats = {
  totalExpensesMtd: 38900.45,
  totalExpensesMtdDelta: "... 12.6% vs last month",
  totalExpensesMtdDeltaColor: "red",
  totalExpensesYtd: 142450.15,
  totalExpensesYtdDelta: "... 8.4% vs last year",
  totalExpensesYtdDeltaColor: "red",
  averageDailyExpense: 1227.42,
  averageDailyExpenseDelta: "... 15.3% vs last month",
  averageDailyExpenseDeltaColor: "green",
  revenuePercentMtd: 20.6,
  revenuePercentMtdDelta: "... 2.1% vs last month",
  revenuePercentMtdDeltaColor: "red",
};

const RECEIPT_URL = "/expenses/sample-receipt.svg";

const VISIBLE_ROWS: ExpenseDetailSeed[] = [
  {
    id: "exp-001",
    date: "2025-05-31",
    category: "vehicle",
    title: "Brake Repair - Stock #1005",
    subtitle: "John's Auto Repair",
    hasReceipt: true,
    paymentMethod: "Credit Card",
    amount: 1850,
    vendor: "John's Auto Repair",
    linkedVehicle: "2019 BMW 3 Series",
    stockNumber: "1005",
    transactionId: "txn_8293012",
    receiptUploadedAt: "2025-05-31T09:15:00",
    notes: null,
    addedBy: "John Dealer",
    description: "Front brake replacement and rotors.",
    createdAt: "2025-05-31T09:15:00",
    receiptImageUrl: RECEIPT_URL,
    vehicleId: null,
  },
  {
    id: "exp-002",
    date: "2025-05-30",
    category: "advertising",
    title: "Facebook Ads - May Campaign",
    subtitle: "Meta Business",
    hasReceipt: true,
    paymentMethod: "Credit Card",
    amount: 750,
    vendor: "Meta Business",
    linkedVehicle: null,
    stockNumber: null,
    transactionId: "txn_8292841",
    receiptUploadedAt: "2025-05-30T14:22:00",
    notes: null,
    addedBy: "Sarah Williams",
    description: "May Facebook and Instagram ad spend.",
    createdAt: "2025-05-30T14:22:00",
    receiptImageUrl: null,
    vehicleId: null,
  },
  {
    id: "exp-003",
    date: "2025-05-29",
    category: "accounting",
    title: "Intuit - May 2025",
    subtitle: "Intuit QuickBooks",
    hasReceipt: true,
    paymentMethod: "Credit Card",
    amount: 325,
    vendor: "Intuit QuickBooks",
    linkedVehicle: null,
    stockNumber: null,
    transactionId: "txn_8292701",
    receiptUploadedAt: "2025-05-29T10:05:00",
    notes: null,
    addedBy: "John Dealer",
    description: "QuickBooks Online monthly subscription.",
    createdAt: "2025-05-29T10:05:00",
    receiptImageUrl: null,
    vehicleId: null,
  },
  {
    id: "exp-004",
    date: "2025-05-28",
    category: "office",
    title: "Office Supplies",
    subtitle: "Staples",
    hasReceipt: true,
    paymentMethod: "Check",
    amount: 125,
    vendor: "Staples",
    linkedVehicle: null,
    stockNumber: null,
    transactionId: "txn_8292588",
    receiptUploadedAt: "2025-05-28T16:40:00",
    notes: null,
    addedBy: "Mike Thompson",
    description: "Printer paper, pens, and folders.",
    createdAt: "2025-05-28T16:40:00",
    receiptImageUrl: null,
    vehicleId: null,
  },
  {
    id: "exp-005",
    date: "2025-05-27",
    category: "salary_wages",
    title: "Payroll - May 2025",
    subtitle: "ADP Payroll",
    hasReceipt: true,
    paymentMethod: "ACH",
    amount: 12500,
    vendor: "ADP Payroll",
    linkedVehicle: null,
    stockNumber: null,
    transactionId: "txn_8292401",
    receiptUploadedAt: "2025-05-27T08:00:00",
    notes: null,
    addedBy: "John Dealer",
    description: "Bi-weekly payroll disbursement.",
    createdAt: "2025-05-27T08:00:00",
    receiptImageUrl: null,
    vehicleId: null,
  },
  {
    id: "exp-006",
    date: "2025-05-26",
    category: "recurring",
    title: "Rent - May 2025",
    subtitle: "Premier Properties LLC",
    hasReceipt: true,
    paymentMethod: "ACH",
    amount: 8500,
    vendor: "Premier Properties LLC",
    linkedVehicle: null,
    stockNumber: null,
    transactionId: "txn_8292210",
    receiptUploadedAt: "2025-05-26T09:30:00",
    notes: null,
    addedBy: "John Dealer",
    description: "Monthly lot and office rent.",
    createdAt: "2025-05-26T09:30:00",
    receiptImageUrl: null,
    vehicleId: null,
  },
  {
    id: "exp-007",
    date: "2025-05-25",
    category: "office",
    title: "Internet - May 2025",
    subtitle: "Spectrum Business",
    hasReceipt: true,
    paymentMethod: "Credit Card",
    amount: 150,
    vendor: "Spectrum Business",
    linkedVehicle: null,
    stockNumber: null,
    transactionId: "txn_8292098",
    receiptUploadedAt: "2025-05-25T11:15:00",
    notes: null,
    addedBy: "Sarah Williams",
    description: "Business internet service.",
    createdAt: "2025-05-25T11:15:00",
    receiptImageUrl: null,
    vehicleId: null,
  },
  {
    id: "exp-008",
    date: "2025-05-24",
    category: "accounting",
    title: "QuickBooks - May 2025",
    subtitle: "Intuit",
    hasReceipt: true,
    paymentMethod: "Credit Card",
    amount: 275,
    vendor: "Intuit",
    linkedVehicle: null,
    stockNumber: null,
    transactionId: "txn_8291987",
    receiptUploadedAt: "2025-05-24T13:50:00",
    notes: null,
    addedBy: "John Dealer",
    description: "QuickBooks add-on services.",
    createdAt: "2025-05-24T13:50:00",
    receiptImageUrl: null,
    vehicleId: null,
  },
  {
    id: "exp-009",
    date: "2025-05-23",
    category: "vehicle",
    title: "Car Wash Supplies",
    subtitle: "AutoDetail Pro",
    hasReceipt: true,
    paymentMethod: "Cash",
    amount: 85,
    vendor: "AutoDetail Pro",
    linkedVehicle: null,
    stockNumber: null,
    transactionId: "txn_8291876",
    receiptUploadedAt: "2025-05-23T15:20:00",
    notes: null,
    addedBy: "Mike Thompson",
    description: "Detailing chemicals and microfiber towels.",
    createdAt: "2025-05-23T15:20:00",
    receiptImageUrl: null,
    vehicleId: null,
  },
  {
    id: "exp-010",
    date: "2025-05-22",
    category: "recurring",
    title: "Insurance - May 2025",
    subtitle: "State Farm Business",
    hasReceipt: true,
    paymentMethod: "ACH",
    amount: 625,
    vendor: "State Farm Business",
    linkedVehicle: null,
    stockNumber: null,
    transactionId: "txn_8291765",
    receiptUploadedAt: "2025-05-22T10:00:00",
    notes: null,
    addedBy: "John Dealer",
    description: "Dealer garage liability insurance.",
    createdAt: "2025-05-22T10:00:00",
    receiptImageUrl: null,
    vehicleId: null,
  },
];

function buildAdditionalExpenses(): ExpenseDetailSeed[] {
  const extras: Omit<ExpenseDetailSeed, "id">[] = [
    {
      date: "2025-05-21",
      category: "vehicle",
      title: "Oil Change - Stock #1012",
      subtitle: "Jiffy Lube",
      hasReceipt: true,
      paymentMethod: "Credit Card",
      amount: 89.99,
      vendor: "Jiffy Lube",
      linkedVehicle: "2021 Honda Civic",
      stockNumber: "1012",
      transactionId: "txn_8291654",
      receiptUploadedAt: "2025-05-21T11:30:00",
      notes: null,
      addedBy: "Mike Thompson",
      description: "Full synthetic oil change.",
      createdAt: "2025-05-21T11:30:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-20",
      category: "advertising",
      title: "Google Ads - May",
      subtitle: "Google",
      hasReceipt: true,
      paymentMethod: "Credit Card",
      amount: 1200,
      vendor: "Google",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8291543",
      receiptUploadedAt: "2025-05-20T09:00:00",
      notes: null,
      addedBy: "Sarah Williams",
      description: "Search and display ad campaign.",
      createdAt: "2025-05-20T09:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-19",
      category: "office",
      title: "Water Delivery",
      subtitle: "Crystal Springs",
      hasReceipt: false,
      paymentMethod: "Check",
      amount: 45,
      vendor: "Crystal Springs",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8291432",
      receiptUploadedAt: null,
      notes: null,
      addedBy: "Sarah Williams",
      description: "Office water cooler refill.",
      createdAt: "2025-05-19T14:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-18",
      category: "vehicle",
      title: "Tire Replacement - Stock #1008",
      subtitle: "Discount Tire",
      hasReceipt: true,
      paymentMethod: "Credit Card",
      amount: 680,
      vendor: "Discount Tire",
      linkedVehicle: "2020 Toyota Camry",
      stockNumber: "1008",
      transactionId: "txn_8291321",
      receiptUploadedAt: "2025-05-18T16:00:00",
      notes: null,
      addedBy: "John Dealer",
      description: "Four new all-season tires.",
      createdAt: "2025-05-18T16:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-17",
      category: "recurring",
      title: "Phone System - May 2025",
      subtitle: "RingCentral",
      hasReceipt: true,
      paymentMethod: "ACH",
      amount: 199,
      vendor: "RingCentral",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8291210",
      receiptUploadedAt: "2025-05-17T08:00:00",
      notes: null,
      addedBy: "John Dealer",
      description: "VoIP phone system subscription.",
      createdAt: "2025-05-17T08:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-16",
      category: "salary_wages",
      title: "Commission Payout",
      subtitle: "Internal",
      hasReceipt: false,
      paymentMethod: "ACH",
      amount: 3200,
      vendor: "Internal",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8291099",
      receiptUploadedAt: null,
      notes: "May commission cycle",
      addedBy: "John Dealer",
      description: "Sales rep commission disbursement.",
      createdAt: "2025-05-16T17:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-15",
      category: "accounting",
      title: "CPA Services - Q1 Review",
      subtitle: "Martinez & Associates",
      hasReceipt: true,
      paymentMethod: "Check",
      amount: 1500,
      vendor: "Martinez & Associates",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8290988",
      receiptUploadedAt: "2025-05-15T12:00:00",
      notes: null,
      addedBy: "John Dealer",
      description: "Quarterly financial review.",
      createdAt: "2025-05-15T12:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-14",
      category: "vehicle",
      title: "Paint Touch-Up - Stock #1003",
      subtitle: "Pro Auto Body",
      hasReceipt: true,
      paymentMethod: "Credit Card",
      amount: 450,
      vendor: "Pro Auto Body",
      linkedVehicle: "2018 Ford F-150",
      stockNumber: "1003",
      transactionId: "txn_8290877",
      receiptUploadedAt: "2025-05-14T10:30:00",
      notes: null,
      addedBy: "Mike Thompson",
      description: "Minor scratch and dent repair.",
      createdAt: "2025-05-14T10:30:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-13",
      category: "advertising",
      title: "AutoTrader Listing - May",
      subtitle: "AutoTrader",
      hasReceipt: true,
      paymentMethod: "Credit Card",
      amount: 899,
      vendor: "AutoTrader",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8290766",
      receiptUploadedAt: "2025-05-13T09:00:00",
      notes: null,
      addedBy: "Sarah Williams",
      description: "Premium inventory listing package.",
      createdAt: "2025-05-13T09:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-12",
      category: "office",
      title: "Cleaning Service",
      subtitle: "Sparkle Clean Co.",
      hasReceipt: true,
      paymentMethod: "Check",
      amount: 350,
      vendor: "Sparkle Clean Co.",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8290655",
      receiptUploadedAt: "2025-05-12T18:00:00",
      notes: null,
      addedBy: "Sarah Williams",
      description: "Monthly office and showroom cleaning.",
      createdAt: "2025-05-12T18:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-11",
      category: "recurring",
      title: "Security System - May 2025",
      subtitle: "ADT Commercial",
      hasReceipt: true,
      paymentMethod: "ACH",
      amount: 175,
      vendor: "ADT Commercial",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8290544",
      receiptUploadedAt: "2025-05-11T08:00:00",
      notes: null,
      addedBy: "John Dealer",
      description: "Lot and building security monitoring.",
      createdAt: "2025-05-11T08:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-10",
      category: "vehicle",
      title: "Transmission Repair - Stock #1015",
      subtitle: "AAMCO",
      hasReceipt: true,
      paymentMethod: "Credit Card",
      amount: 2200,
      vendor: "AAMCO",
      linkedVehicle: "2017 Chevrolet Silverado",
      stockNumber: "1015",
      transactionId: "txn_8290433",
      receiptUploadedAt: "2025-05-10T14:00:00",
      notes: null,
      addedBy: "John Dealer",
      description: "Transmission rebuild and fluid flush.",
      createdAt: "2025-05-10T14:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-09",
      category: "office",
      title: "Coffee & Snacks",
      subtitle: "Costco Business",
      hasReceipt: true,
      paymentMethod: "Credit Card",
      amount: 78.5,
      vendor: "Costco Business",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8290322",
      receiptUploadedAt: "2025-05-09T11:00:00",
      notes: null,
      addedBy: "Mike Thompson",
      description: "Break room supplies for the month.",
      createdAt: "2025-05-09T11:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-08",
      category: "advertising",
      title: "Billboard Rental - May",
      subtitle: "Clear Channel Outdoor",
      hasReceipt: true,
      paymentMethod: "Check",
      amount: 2500,
      vendor: "Clear Channel Outdoor",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8290211",
      receiptUploadedAt: "2025-05-08T10:00:00",
      notes: null,
      addedBy: "Sarah Williams",
      description: "Highway billboard advertising.",
      createdAt: "2025-05-08T10:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-07",
      category: "accounting",
      title: "Bank Fees - May 2025",
      subtitle: "Chase Business",
      hasReceipt: true,
      paymentMethod: "ACH",
      amount: 45,
      vendor: "Chase Business",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8290100",
      receiptUploadedAt: "2025-05-07T08:00:00",
      notes: null,
      addedBy: "John Dealer",
      description: "Monthly business account fees.",
      createdAt: "2025-05-07T08:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-06",
      category: "vehicle",
      title: "Detailing - Stock #1020",
      subtitle: "Elite Auto Spa",
      hasReceipt: true,
      paymentMethod: "Credit Card",
      amount: 275,
      vendor: "Elite Auto Spa",
      linkedVehicle: "2022 Tesla Model 3",
      stockNumber: "1020",
      transactionId: "txn_8289989",
      receiptUploadedAt: "2025-05-06T15:00:00",
      notes: null,
      addedBy: "Mike Thompson",
      description: "Full interior and exterior detail.",
      createdAt: "2025-05-06T15:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-05",
      category: "salary_wages",
      title: "Payroll - May 2025 (2nd)",
      subtitle: "ADP Payroll",
      hasReceipt: true,
      paymentMethod: "ACH",
      amount: 12500,
      vendor: "ADP Payroll",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8289878",
      receiptUploadedAt: "2025-05-05T08:00:00",
      notes: null,
      addedBy: "John Dealer",
      description: "Second bi-weekly payroll disbursement.",
      createdAt: "2025-05-05T08:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-04",
      category: "recurring",
      title: "Lot Maintenance - May 2025",
      subtitle: "GreenScape Services",
      hasReceipt: true,
      paymentMethod: "Check",
      amount: 400,
      vendor: "GreenScape Services",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8289767",
      receiptUploadedAt: "2025-05-04T09:00:00",
      notes: null,
      addedBy: "John Dealer",
      description: "Landscaping and lot upkeep.",
      createdAt: "2025-05-04T09:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-03",
      category: "office",
      title: "Printer Toner",
      subtitle: "Office Depot",
      hasReceipt: true,
      paymentMethod: "Credit Card",
      amount: 189,
      vendor: "Office Depot",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8289656",
      receiptUploadedAt: "2025-05-03T13:00:00",
      notes: null,
      addedBy: "Sarah Williams",
      description: "Replacement toner cartridges.",
      createdAt: "2025-05-03T13:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-02",
      category: "vehicle",
      title: "Battery Replacement - Stock #1007",
      subtitle: "AutoZone",
      hasReceipt: true,
      paymentMethod: "Credit Card",
      amount: 165,
      vendor: "AutoZone",
      linkedVehicle: "2019 Nissan Altima",
      stockNumber: "1007",
      transactionId: "txn_8289545",
      receiptUploadedAt: "2025-05-02T11:00:00",
      notes: null,
      addedBy: "Mike Thompson",
      description: "New battery and installation.",
      createdAt: "2025-05-02T11:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-05-01",
      category: "advertising",
      title: "Cars.com Listing - May",
      subtitle: "Cars.com",
      hasReceipt: true,
      paymentMethod: "Credit Card",
      amount: 599,
      vendor: "Cars.com",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8289434",
      receiptUploadedAt: "2025-05-01T09:00:00",
      notes: null,
      addedBy: "Sarah Williams",
      description: "Inventory syndication package.",
      createdAt: "2025-05-01T09:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-04-30",
      category: "accounting",
      title: "Tax Prep Software",
      subtitle: "TurboTax Business",
      hasReceipt: true,
      paymentMethod: "Credit Card",
      amount: 199,
      vendor: "TurboTax Business",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8289323",
      receiptUploadedAt: "2025-04-30T10:00:00",
      notes: null,
      addedBy: "John Dealer",
      description: "Annual tax preparation software license.",
      createdAt: "2025-04-30T10:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-04-29",
      category: "vehicle",
      title: "Windshield Replacement - Stock #1018",
      subtitle: "Safelite AutoGlass",
      hasReceipt: true,
      paymentMethod: "Credit Card",
      amount: 395,
      vendor: "Safelite AutoGlass",
      linkedVehicle: "2020 Jeep Wrangler",
      stockNumber: "1018",
      transactionId: "txn_8289212",
      receiptUploadedAt: "2025-04-29T14:00:00",
      notes: null,
      addedBy: "Mike Thompson",
      description: "Front windshield replacement.",
      createdAt: "2025-04-29T14:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-04-28",
      category: "recurring",
      title: "Waste Disposal - April 2025",
      subtitle: "Waste Management",
      hasReceipt: true,
      paymentMethod: "ACH",
      amount: 220,
      vendor: "Waste Management",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8289101",
      receiptUploadedAt: "2025-04-28T08:00:00",
      notes: null,
      addedBy: "John Dealer",
      description: "Commercial waste pickup service.",
      createdAt: "2025-04-28T08:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-04-27",
      category: "office",
      title: "Business Cards Reprint",
      subtitle: "Vistaprint",
      hasReceipt: true,
      paymentMethod: "Credit Card",
      amount: 95,
      vendor: "Vistaprint",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8288990",
      receiptUploadedAt: "2025-04-27T16:00:00",
      notes: null,
      addedBy: "Sarah Williams",
      description: "New sales team business cards.",
      createdAt: "2025-04-27T16:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-04-26",
      category: "vehicle",
      title: "AC Repair - Stock #1011",
      subtitle: "Firestone Complete Auto",
      hasReceipt: true,
      paymentMethod: "Credit Card",
      amount: 520,
      vendor: "Firestone Complete Auto",
      linkedVehicle: "2018 Mazda CX-5",
      stockNumber: "1011",
      transactionId: "txn_8288879",
      receiptUploadedAt: "2025-04-26T12:00:00",
      notes: null,
      addedBy: "John Dealer",
      description: "AC compressor recharge and leak repair.",
      createdAt: "2025-04-26T12:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-04-25",
      category: "advertising",
      title: "Direct Mail Campaign",
      subtitle: "USPS Every Door",
      hasReceipt: true,
      paymentMethod: "Check",
      amount: 1100,
      vendor: "USPS Every Door",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8288768",
      receiptUploadedAt: "2025-04-25T09:00:00",
      notes: null,
      addedBy: "Sarah Williams",
      description: "Neighborhood direct mail flyers.",
      createdAt: "2025-04-25T09:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-04-24",
      category: "salary_wages",
      title: "Bonus Payout - Q1",
      subtitle: "Internal",
      hasReceipt: false,
      paymentMethod: "ACH",
      amount: 5000,
      vendor: "Internal",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8288657",
      receiptUploadedAt: null,
      notes: "Q1 performance bonuses",
      addedBy: "John Dealer",
      description: "Quarterly sales team bonus disbursement.",
      createdAt: "2025-04-24T17:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-04-23",
      category: "accounting",
      title: "Payroll Tax Filing",
      subtitle: "ADP Tax Services",
      hasReceipt: true,
      paymentMethod: "ACH",
      amount: 850,
      vendor: "ADP Tax Services",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8288546",
      receiptUploadedAt: "2025-04-23T08:00:00",
      notes: null,
      addedBy: "John Dealer",
      description: "Quarterly payroll tax filing service.",
      createdAt: "2025-04-23T08:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-04-22",
      category: "vehicle",
      title: "Alignment - Stock #1009",
      subtitle: "Big O Tires",
      hasReceipt: true,
      paymentMethod: "Credit Card",
      amount: 120,
      vendor: "Big O Tires",
      linkedVehicle: "2021 Subaru Outback",
      stockNumber: "1009",
      transactionId: "txn_8288435",
      receiptUploadedAt: "2025-04-22T14:00:00",
      notes: null,
      addedBy: "Mike Thompson",
      description: "Four-wheel alignment service.",
      createdAt: "2025-04-22T14:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-04-21",
      category: "recurring",
      title: "CRM Subscription - April 2025",
      subtitle: "AutoVault",
      hasReceipt: true,
      paymentMethod: "Credit Card",
      amount: 299,
      vendor: "AutoVault",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8288324",
      receiptUploadedAt: "2025-04-21T08:00:00",
      notes: null,
      addedBy: "John Dealer",
      description: "Dealer management software subscription.",
      createdAt: "2025-04-21T08:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-04-20",
      category: "office",
      title: "Furniture - Showroom Chairs",
      subtitle: "Office Furniture Outlet",
      hasReceipt: true,
      paymentMethod: "Check",
      amount: 1450,
      vendor: "Office Furniture Outlet",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8288213",
      receiptUploadedAt: "2025-04-20T11:00:00",
      notes: null,
      addedBy: "Sarah Williams",
      description: "Customer waiting area seating.",
      createdAt: "2025-04-20T11:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-04-19",
      category: "vehicle",
      title: "Smog Check - Stock #1014",
      subtitle: "Star Smog Station",
      hasReceipt: true,
      paymentMethod: "Cash",
      amount: 65,
      vendor: "Star Smog Station",
      linkedVehicle: "2016 Honda Accord",
      stockNumber: "1014",
      transactionId: "txn_8288102",
      receiptUploadedAt: "2025-04-19T10:00:00",
      notes: null,
      addedBy: "Mike Thompson",
      description: "California smog certification.",
      createdAt: "2025-04-19T10:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-04-18",
      category: "advertising",
      title: "Radio Spot - April",
      subtitle: "KFI AM 640",
      hasReceipt: true,
      paymentMethod: "Check",
      amount: 1800,
      vendor: "KFI AM 640",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8287991",
      receiptUploadedAt: "2025-04-18T09:00:00",
      notes: null,
      addedBy: "Sarah Williams",
      description: "Weekly radio advertising spots.",
      createdAt: "2025-04-18T09:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-04-17",
      category: "accounting",
      title: "Merchant Processing Fees",
      subtitle: "Square",
      hasReceipt: true,
      paymentMethod: "ACH",
      amount: 312.45,
      vendor: "Square",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8287880",
      receiptUploadedAt: "2025-04-17T08:00:00",
      notes: null,
      addedBy: "John Dealer",
      description: "Credit card processing fees for April.",
      createdAt: "2025-04-17T08:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-04-16",
      category: "recurring",
      title: "Electricity - April 2025",
      subtitle: "Southern California Edison",
      hasReceipt: true,
      paymentMethod: "ACH",
      amount: 890,
      vendor: "Southern California Edison",
      linkedVehicle: null,
      stockNumber: null,
      transactionId: "txn_8287769",
      receiptUploadedAt: "2025-04-16T08:00:00",
      notes: null,
      addedBy: "John Dealer",
      description: "Monthly electricity bill.",
      createdAt: "2025-04-16T08:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
    {
      date: "2025-04-15",
      category: "vehicle",
      title: "Key Fob Programming - Stock #1016",
      subtitle: "Dealership Key Service",
      hasReceipt: true,
      paymentMethod: "Credit Card",
      amount: 145,
      vendor: "Dealership Key Service",
      linkedVehicle: "2020 BMW X5",
      stockNumber: "1016",
      transactionId: "txn_8287658",
      receiptUploadedAt: "2025-04-15T13:00:00",
      notes: null,
      addedBy: "Mike Thompson",
      description: "Replacement key fob programming.",
      createdAt: "2025-04-15T13:00:00",
      receiptImageUrl: null,
      vehicleId: null,
    },
  ];

  return extras.map((item, index) => ({
    ...item,
    id: `exp-${String(index + 11).padStart(3, "0")}`,
  }));
}

export const EXPENSES_MOCK: ExpenseDetail[] = [
  ...VISIBLE_ROWS,
  ...buildAdditionalExpenses(),
].map(withExpenseKind);
