import { CALENDAR_MOCK_REPORT } from "@/lib/calendar/mock-data";
import type { AdminDashboardContentProps, AdminTodayEvent } from "./types";

const VEHICLE_IMG =
  "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=400&h=300&fit=crop";

function formatPeriodLabel(from: string, to: string): string {
  const fromDate = new Date(`${from}T12:00:00`);
  const toDate = new Date(`${to}T12:00:00`);
  const fromPart = fromDate.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
  });
  const toPart = toDate.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
  return `${fromPart} - ${toPart}`;
}

function buildTodayEvents(today: string): AdminTodayEvent[] {
  const day = CALENDAR_MOCK_REPORT.dailyActivity.find((d) => d.date === today);
  if (day && day.events.length > 0) {
    return day.events.map((event) => ({
      id: event.id,
      time: event.time,
      title: event.title,
      type: event.type,
    }));
  }

  return [
    {
      id: "te-1",
      time: "10:00 AM",
      title: "Customer Appointment - VIN 1234",
      type: "appointment",
    },
    {
      id: "te-2",
      time: "2:00 PM",
      title: "Bank Funding Review",
      type: "task",
    },
    {
      id: "te-3",
      time: "3:30 PM",
      title: "Sales Team Meeting",
      type: "task",
    },
  ];
}

const BASE_MOCK: Omit<
  AdminDashboardContentProps,
  "periodLabel" | "grossProfitPeriodLabel" | "calendarReport" | "todayEvents"
> = {
  kpiCards: [
    {
      icon: "car",
      color: "blue",
      label: "Vehicles in Inventory",
      value: "42",
      unit: "Total Value: $1,264,580",
      link: "View Inventory",
      sparkColor: "#3b82f6",
      sparkPoints:
        "0,32 25,28 50,30 75,26 100,24 125,22 150,20 175,18 200,16",
    },
    {
      icon: "car",
      color: "green",
      label: "Vehicles Sold This Month",
      value: "18",
      unit: "Total Sales: $602,450",
      link: "View Sales",
      sparkColor: "#22c55e",
      sparkPoints:
        "0,28 25,24 50,26 75,22 100,20 125,18 150,16 175,14 200,12",
    },
    {
      icon: "dollar-sign",
      color: "violet",
      label: "Total Retail Revenue",
      value: "$602,450",
      delta: "+ 18.6% vs last month",
      link: "View Revenue",
      sparkColor: "#a855f7",
      sparkPoints:
        "0,36 25,32 50,28 75,26 100,22 125,20 150,16 175,14 200,12",
    },
    {
      icon: "trending-down",
      color: "red",
      label: "Total Expenses",
      value: "$176,480",
      delta: "- 8.4% vs last month",
      link: "View Expenses",
      sparkColor: "#ef4444",
      sparkPoints:
        "0,32 25,30 50,28 75,26 100,24 125,22 150,20 175,18 200,16",
    },
    {
      icon: "pie-chart",
      color: "green",
      label: "Gross Profit",
      value: "$425,970",
      delta: "+ 22.2% vs last month",
      link: "View Details",
      sparkColor: "#22c55e",
      sparkPoints:
        "0,40 25,34 50,30 75,26 100,24 125,18 150,16 175,12 200,10",
    },
    {
      icon: "bar-chart-3",
      color: "blue",
      label: "Net Profit",
      value: "$326,110",
      delta: "+ 20.1% vs last month",
      link: "View Details",
      sparkColor: "#3b82f6",
      sparkPoints:
        "0,36 25,32 50,28 75,24 100,22 125,18 150,16 175,12 200,10",
    },
    {
      icon: "handshake",
      color: "amber",
      label: "Pending Deal Jackets",
      value: "8",
      unit: "Requires Review",
      link: "View Deal Jackets",
      sparkColor: "#f59e0b",
      sparkPoints:
        "0,38 25,34 50,30 75,28 100,26 125,24 150,22 175,20 200,18",
    },
  ],
  inventoryVehicles: [
    {
      id: "inv-1",
      vin: "1HGCM82633A004352",
      year: 2022,
      make: "Toyota",
      model: "Camry",
      stockNumber: "STK-001",
      costs: {
        acquisition: 18000,
        auction: 0,
        transport: 500,
        recon: 1200,
        storage: 300,
        dealerFees: 200,
      },
      marketValue: 22500,
      status: "in_inventory",
      daysInLot: 15,
      purchaseDate: "2026-05-25",
      imageUrl: VEHICLE_IMG,
    },
    {
      id: "inv-2",
      vin: "2HGFG3B53GH550001",
      year: 2023,
      make: "Honda",
      model: "Accord",
      stockNumber: "STK-002",
      costs: {
        acquisition: 19500,
        auction: 0,
        transport: 400,
        recon: 800,
        storage: 200,
        dealerFees: 150,
      },
      marketValue: 24500,
      status: "in_inventory",
      daysInLot: 22,
      purchaseDate: "2026-05-18",
      imageUrl: VEHICLE_IMG,
    },
    {
      id: "inv-3",
      vin: "3FA6P0HD5KR123456",
      year: 2021,
      make: "Ford",
      model: "F-150",
      stockNumber: "STK-003",
      costs: {
        acquisition: 28000,
        auction: 0,
        transport: 600,
        recon: 2500,
        storage: 400,
        dealerFees: 300,
      },
      marketValue: 36500,
      status: "in_inventory",
      daysInLot: 8,
      purchaseDate: "2026-06-01",
      imageUrl: VEHICLE_IMG,
    },
    {
      id: "inv-4",
      vin: "4T1BF1FK4GU123456",
      year: 2020,
      make: "Chevrolet",
      model: "Tahoe",
      stockNumber: "STK-004",
      costs: {
        acquisition: 32000,
        auction: 0,
        transport: 700,
        recon: 1800,
        storage: 500,
        dealerFees: 250,
      },
      marketValue: 42000,
      status: "in_inventory",
      daysInLot: 35,
      purchaseDate: "2026-05-05",
      imageUrl: VEHICLE_IMG,
    },
    {
      id: "inv-5",
      vin: "5YJSA1E26HF123456",
      year: 2024,
      make: "Tesla",
      model: "Model 3",
      stockNumber: "STK-005",
      costs: {
        acquisition: 35000,
        auction: 0,
        transport: 300,
        recon: 200,
        storage: 100,
        dealerFees: 100,
      },
      marketValue: 42000,
      status: "in_inventory",
      daysInLot: 3,
      purchaseDate: "2026-06-06",
      imageUrl: VEHICLE_IMG,
    },
  ],
  profitLossPoints: [
    { week: "Week 1", revenue: 148600, expenses: 42100 },
    { week: "Week 2", revenue: 132400, expenses: 39800 },
    { week: "Week 3", revenue: 168200, expenses: 51200 },
    { week: "Week 4", revenue: 153250, expenses: 43380 },
  ],
  profitLossSummary: {
    totalRevenue: 602450,
    totalExpenses: 176480,
    netProfit: 326110,
  },
  activities: [
    {
      id: "act-1",
      action: "Sold 2022 Toyota Camry",
      detail: "John Smith | $28,500",
      timestamp: "2 hours ago",
      icon: "sold",
    },
    {
      id: "act-2",
      action: "Sold 2023 Honda Accord",
      detail: "Jane Doe | $26,200",
      timestamp: "4 hours ago",
      icon: "sold",
    },
    {
      id: "act-3",
      action: "New inventory added",
      detail: "2024 Tesla Model 3",
      timestamp: "Yesterday",
      icon: "inventory",
    },
    {
      id: "act-4",
      action: "Expense logged",
      detail: "Vehicle Repairs - $1,250",
      timestamp: "Yesterday",
      icon: "expense",
    },
    {
      id: "act-5",
      action: "Deal jacket completed",
      detail: "STK-001 - Toyota Camry",
      timestamp: "2 days ago",
      icon: "document",
    },
    {
      id: "act-6",
      action: "Commission paid",
      detail: "Mike Thompson | $5,752",
      timestamp: "2 days ago",
      icon: "document",
    },
  ],
  topVehicle: {
    title: "2022 Toyota Camry",
    vin: "1HGCM82633A004352",
    profit: 8500,
    img: VEHICLE_IMG,
  },
  topVehicleUnitsSold: 4,
  topSalesRep: {
    id: "sr-1",
    fullName: "Mike Thompson",
    email: "mike@autovault.com",
    phone: "(555) 123-4567",
    imageUrl: null,
    isActive: true,
    commissionRate: 20,
    monthlyGoal: 10,
    unitsSold: 18,
    unitsSoldDelta: "+22%",
    unitsSoldDeltaColor: "green",
    unitsSoldSparkPoints: "0,8 25,10 50,12 75,14 100,16 125,18",
    grossProfit: 28760,
    grossProfitDelta: "+18%",
    grossProfitDeltaColor: "green",
    grossProfitSparkPoints: "0,12 25,14 50,16 75,18 100,20 125,22",
    netProfit: 15200,
    netProfitDelta: "+15%",
    netProfitDeltaColor: "green",
    netProfitSparkPoints: "0,10 25,12 50,14 75,16 100,18 125,20",
    totalSales: 182000,
    totalSalesDelta: "+20%",
    totalSalesDeltaColor: "green",
    totalSalesSparkPoints: "0,14 25,16 50,18 75,20 100,22 125,24",
    avgGrossPerUnit: 1598,
    avgGrossDelta: "+5%",
    avgGrossDeltaColor: "green",
    avgGrossSparkPoints: "0,6 25,7 50,8 75,9 100,10 125,11",
    conversionRate: 28.6,
    conversionDelta: "+3.2%",
    conversionDeltaColor: "green",
    conversionSparkPoints: "0,22 25,23 50,24 75,25 100,26 125,27",
    goalAmount: 150000,
    goalProgress: 121,
    status: "top_performer",
  },
  salesRepKpis: [
    {
      icon: "car",
      color: "blue",
      label: "Total Cars Sold",
      value: "18",
      delta: "+12% vs last month",
      link: "View Details",
      sparkColor: "#3b82f6",
      sparkPoints: "",
    },
    {
      icon: "dollar-sign",
      color: "green",
      label: "Gross Profit Generated",
      value: "$425,970",
      delta: "+22% vs last month",
      link: "View Details",
      sparkColor: "#22c55e",
      sparkPoints: "",
    },
    {
      icon: "percent",
      color: "green",
      label: "Total Commission Earned",
      value: "$24,680",
      delta: "+15% vs last month",
      link: "View Details",
      sparkColor: "#22c55e",
      sparkPoints: "",
    },
    {
      icon: "tag",
      color: "amber",
      label: "Pending Commission",
      value: "$4,820",
      unit: "3 Deals Pending",
      link: "View Details",
      sparkColor: "#f59e0b",
      sparkPoints: "",
    },
    {
      icon: "dollar-sign",
      color: "green",
      label: "Paid Commission",
      value: "$19,860",
      delta: "+12% vs last month",
      link: "View Details",
      sparkColor: "#22c55e",
      sparkPoints: "",
    },
  ],
  salesRepTableRows: [
    {
      rank: 1,
      id: "sr-1",
      name: "Mike Thompson",
      imageUrl: null,
      carsSold: 18,
      grossProfit: 28760,
      commissionEarned: 5752,
      pendingCommission: 0,
      payrollStatus: "Paid",
    },
    {
      rank: 2,
      id: "sr-2",
      name: "Sarah Williams",
      imageUrl: null,
      carsSold: 16,
      grossProfit: 25840,
      commissionEarned: 5168,
      pendingCommission: 1200,
      payrollStatus: "Pending",
    },
    {
      rank: 3,
      id: "sr-3",
      name: "Chris Allen",
      imageUrl: null,
      carsSold: 14,
      grossProfit: 21390,
      commissionEarned: 4278,
      pendingCommission: 0,
      payrollStatus: "Paid",
    },
    {
      rank: 4,
      id: "sr-4",
      name: "David Martinez",
      imageUrl: null,
      carsSold: 12,
      grossProfit: 18650,
      commissionEarned: 3730,
      pendingCommission: 850,
      payrollStatus: "Pending",
    },
    {
      rank: 5,
      id: "sr-5",
      name: "Emily Davis",
      imageUrl: null,
      carsSold: 10,
      grossProfit: 15780,
      commissionEarned: 3156,
      pendingCommission: 0,
      payrollStatus: "Paid",
    },
    {
      rank: 6,
      id: "sr-6",
      name: "James Wilson",
      imageUrl: null,
      carsSold: 8,
      grossProfit: 12450,
      commissionEarned: 2490,
      pendingCommission: 620,
      payrollStatus: "Pending",
    },
  ],
  salesRepStats: {
    totalReps: 12,
    activeReps: 10,
    commissionsPaidMtd: 19860,
    commissionsPaidMtdDelta: "+12.5%",
    commissionsPaidMtdDeltaColor: "green",
    commissionsPaidMtdSparkPoints: "",
    totalCommissionsYtd: 98500,
    totalCommissionsYtdDelta: "+18.3%",
    totalCommissionsYtdDeltaColor: "green",
    totalCommissionsYtdSparkPoints: "",
  },
  grossProfitRows: [
    {
      id: "gp-1",
      vehicleLabel: "2022 Toyota Camry",
      imageUrl: VEHICLE_IMG,
      stockNumber: "STK-001",
      saleDate: "2026-06-09",
      purchaseCost: 18000,
      reconCost: 1200,
      totalCost: 20000,
      salePrice: 28500,
      grossProfit: 8500,
      commissionRate: 20,
      commissionEarned: 1700,
      salesRepId: "sr-1",
      dealType: "financed",
    },
    {
      id: "gp-2",
      vehicleLabel: "2023 Honda Accord",
      imageUrl: VEHICLE_IMG,
      stockNumber: "STK-002",
      saleDate: "2026-06-09",
      purchaseCost: 19500,
      reconCost: 800,
      totalCost: 20900,
      salePrice: 26200,
      grossProfit: 5300,
      commissionRate: 20,
      commissionEarned: 1060,
      salesRepId: "sr-2",
      dealType: "cash",
    },
    {
      id: "gp-3",
      vehicleLabel: "2021 Ford F-150",
      imageUrl: VEHICLE_IMG,
      stockNumber: "STK-003",
      saleDate: "2026-06-07",
      purchaseCost: 28000,
      reconCost: 2500,
      totalCost: 31300,
      salePrice: 38500,
      grossProfit: 7200,
      commissionRate: 20,
      commissionEarned: 1440,
      salesRepId: "sr-1",
      dealType: "financed",
    },
    {
      id: "gp-4",
      vehicleLabel: "2020 Chevrolet Tahoe",
      imageUrl: VEHICLE_IMG,
      stockNumber: "STK-004",
      saleDate: "2026-06-06",
      purchaseCost: 32000,
      reconCost: 1800,
      totalCost: 34500,
      salePrice: 42800,
      grossProfit: 8300,
      commissionRate: 20,
      commissionEarned: 1660,
      salesRepId: "sr-3",
      dealType: "financed",
    },
    {
      id: "gp-5",
      vehicleLabel: "2024 Tesla Model 3",
      imageUrl: VEHICLE_IMG,
      stockNumber: "STK-005",
      saleDate: "2026-06-05",
      purchaseCost: 35000,
      reconCost: 200,
      totalCost: 35600,
      salePrice: 41200,
      grossProfit: 5600,
      commissionRate: 20,
      commissionEarned: 1120,
      salesRepId: "sr-2",
      dealType: "cash",
    },
    {
      id: "gp-6",
      vehicleLabel: "2019 BMW 3 Series",
      imageUrl: VEHICLE_IMG,
      stockNumber: "STK-006",
      saleDate: "2026-06-04",
      purchaseCost: 22000,
      reconCost: 1400,
      totalCost: 23600,
      salePrice: 29800,
      grossProfit: 6200,
      commissionRate: 20,
      commissionEarned: 1240,
      salesRepId: "sr-4",
      dealType: "financed",
    },
    {
      id: "gp-7",
      vehicleLabel: "2022 Jeep Wrangler",
      imageUrl: VEHICLE_IMG,
      stockNumber: "STK-007",
      saleDate: "2026-06-03",
      purchaseCost: 26500,
      reconCost: 2100,
      totalCost: 28900,
      salePrice: 35200,
      grossProfit: 6300,
      commissionRate: 20,
      commissionEarned: 1260,
      salesRepId: "sr-1",
      dealType: "financed",
    },
    {
      id: "gp-8",
      vehicleLabel: "2021 Nissan Altima",
      imageUrl: VEHICLE_IMG,
      stockNumber: "STK-008",
      saleDate: "2026-06-02",
      purchaseCost: 14200,
      reconCost: 900,
      totalCost: 15400,
      salePrice: 19800,
      grossProfit: 4400,
      commissionRate: 20,
      commissionEarned: 880,
      salesRepId: "sr-5",
      dealType: "cash",
    },
  ],
  stickyNotes: [
    {
      id: "n-1",
      color: "#fef08a",
      text: "Follow up with CPA on Q1 filings before month end.",
      date: "Jun 8, 2026",
      author: "John Dealer",
    },
    {
      id: "n-2",
      color: "#bbf7d0",
      text: "Review floor plan interest on 60+ day units.",
      date: "Jun 7, 2026",
      author: "Sarah Williams",
    },
    {
      id: "n-3",
      color: "#bfdbfe",
      text: "Schedule marketing vendor contract review.",
      date: "Jun 6, 2026",
      author: "Mike Thompson",
    },
    {
      id: "n-4",
      color: "#fbcfe8",
      text: "Confirm CDTFA payment posted for April filing.",
      date: "Jun 5, 2026",
      author: "John Dealer",
    },
  ],
};

export function buildAdminDashboardMock(opts?: {
  periodFrom?: string;
  periodTo?: string;
  today?: string;
}): AdminDashboardContentProps {
  const today = opts?.today ?? new Date().toISOString().slice(0, 10);
  const periodFrom =
    opts?.periodFrom ??
    `${today.slice(0, 7)}-01`;
  const periodTo =
    opts?.periodTo ??
    new Date(Number(today.slice(0, 4)), Number(today.slice(5, 7)), 0)
      .toISOString()
      .slice(0, 10);
  const periodLabel = formatPeriodLabel(periodFrom, periodTo);

  return {
    ...BASE_MOCK,
    periodLabel,
    grossProfitPeriodLabel: periodLabel,
    calendarReport: CALENDAR_MOCK_REPORT,
    todayEvents: buildTodayEvents(today),
  };
}

export const ADMIN_DASHBOARD_MOCK: AdminDashboardContentProps =
  buildAdminDashboardMock();
