import type { FilesStorageReport } from "./types";

export const FILES_STORAGE_MOCK: FilesStorageReport = {
  totalStorageGb: 1024,
  usedStorageGb: 632.45,
  totalFiles: 18542,
  totalImages: 12983,
  lastUpload: {
    at: "2025-05-20T10:24:00",
    by: "John Dealer",
  },
  usagePercent: 61.7,
  breakdown: [
    {
      id: "documents",
      label: "Documents",
      color: "#3B82F6",
      sizeGb: 312.45,
      percent: 49.4,
    },
    {
      id: "images",
      label: "Images",
      color: "#22C55E",
      sizeGb: 198.12,
      percent: 31.3,
    },
    {
      id: "videos",
      label: "Videos",
      color: "#A855F7",
      sizeGb: 68.34,
      percent: 10.8,
    },
    {
      id: "other",
      label: "Other",
      color: "#F97316",
      sizeGb: 53.54,
      percent: 8.5,
    },
  ],
  folders: [
    {
      id: "deal-jackets",
      name: "Deal Jackets",
      description: "All deal related documents",
      fileCount: 5432,
      sizeGb: 186.45,
      lastModified: "2025-05-20T10:24:00",
      iconColor: "yellow",
    },
    {
      id: "vehicle-photos",
      name: "Vehicle Photos",
      description: "Vehicle inventory images",
      fileCount: 8765,
      sizeGb: 242.18,
      lastModified: "2025-05-20T09:15:00",
      iconColor: "green",
    },
    {
      id: "expenses-receipts",
      name: "Expenses & Receipts",
      description: "Expense receipts and invoices",
      fileCount: 2341,
      sizeGb: 68.34,
      lastModified: "2025-05-19T16:42:00",
      iconColor: "orange",
    },
    {
      id: "payroll-hr",
      name: "Payroll & HR",
      description: "Payroll and HR documents",
      fileCount: 842,
      sizeGb: 34.67,
      lastModified: "2025-05-18T11:30:00",
      iconColor: "yellow",
    },
    {
      id: "cdtfa-tax",
      name: "CDTFA & Tax Documents",
      description: "Tax filings and CDTFA records",
      fileCount: 562,
      sizeGb: 23.45,
      lastModified: "2025-05-17T14:20:00",
      iconColor: "red",
    },
    {
      id: "contracts-forms",
      name: "Contracts & Forms",
      description: "Contracts and legal forms",
      fileCount: 1245,
      sizeGb: 45.89,
      lastModified: "2025-05-16T09:00:00",
      iconColor: "blue",
    },
    {
      id: "marketing-ads",
      name: "Marketing & Ads",
      description: "Marketing materials and ads",
      fileCount: 987,
      sizeGb: 32.12,
      lastModified: "2025-05-15T13:45:00",
      iconColor: "purple",
    },
    {
      id: "other-files",
      name: "Other Files",
      description: "Miscellaneous files",
      fileCount: 1234,
      sizeGb: 45.67,
      lastModified: "2025-05-14T08:30:00",
      iconColor: "yellow",
    },
  ],
  recentUploads: [
    {
      id: "upload-1",
      fileName: "RO-1012_DealJacket.pdf",
      category: "Deal Jackets",
      uploadedAt: "2025-05-20T10:24:00",
      sizeBytes: 2516582,
      fileType: "pdf",
    },
    {
      id: "upload-2",
      fileName: "VIN_Photo_Front.jpg",
      category: "Vehicle Photos",
      uploadedAt: "2025-05-20T09:15:00",
      sizeBytes: 1887436,
      fileType: "jpg",
    },
    {
      id: "upload-3",
      fileName: "Expense_Receipt_May19.pdf",
      category: "Expenses & Receipts",
      uploadedAt: "2025-05-19T16:42:00",
      sizeBytes: 524288,
      fileType: "pdf",
    },
    {
      id: "upload-4",
      fileName: "Payroll_May2025.xlsx",
      category: "Payroll & HR",
      uploadedAt: "2025-05-18T11:30:00",
      sizeBytes: 1048576,
      fileType: "xlsx",
    },
    {
      id: "upload-5",
      fileName: "Vehicle_Walkaround.mp4",
      category: "Vehicle Photos",
      uploadedAt: "2025-05-17T14:20:00",
      sizeBytes: 15728640,
      fileType: "mp4",
    },
  ],
  storageTips: [
    "Delete old or unused files",
    "Compress large video files",
    "Archive old deal jackets",
    "Review and clean up regularly",
  ],
  aiSuggestions: [
    {
      id: "sug-1",
      label: "Show me all deal jackets from this month",
      icon: "chart",
    },
    {
      id: "sug-2",
      label: "Which expenses are missing receipts?",
      icon: "clock",
    },
    {
      id: "sug-3",
      label: "Show me my top profitable vehicles",
      icon: "dollar",
    },
    {
      id: "sug-4",
      label: "What documents are missing in deal RO-1012?",
      icon: "file",
    },
    {
      id: "sug-5",
      label: "Show me pending CDTFA filings",
      icon: "image",
    },
    {
      id: "sug-6",
      label: "How much storage space do I have left?",
      icon: "cloud",
    },
    {
      id: "sug-7",
      label: "Find all vehicle photos uploaded this week",
      icon: "user",
    },
    {
      id: "sug-8",
      label: "Show me contracts expiring soon",
      icon: "alert",
    },
  ],
};
