import type { RemindersReport } from "./types";

export const REMINDERS_MOCK_REPORT: RemindersReport = {
  reminders: [
    {
      id: "r-1",
      title: "CDTFA Filing Due",
      description: "Q1 2025 sales tax return submission",
      category: "accounting",
      priority: "high",
      dueDate: "2025-05-20",
      completed: false,
      iconColor: "red",
    },
    {
      id: "r-2",
      title: "Vehicle 2020 Honda Accord",
      description: "Smog certificate renewal required",
      category: "vehicle",
      priority: "medium",
      dueDate: "2025-05-20",
      completed: false,
      iconColor: "amber",
    },
    {
      id: "r-3",
      title: "Payroll Due",
      description: "Bi-weekly payroll processing",
      category: "employee",
      priority: "medium",
      dueDate: "2025-05-22",
      completed: false,
      iconColor: "blue",
    },
    {
      id: "r-4",
      title: "Deal Jacket RO-1012",
      description: "Missing buyer ID and smog certificate",
      category: "deal",
      priority: "high",
      dueDate: "2025-05-21",
      completed: false,
      iconColor: "purple",
    },
    {
      id: "r-5",
      title: "Dealer Insurance Renewal",
      description: "Annual policy renewal deadline",
      category: "business",
      priority: "high",
      dueDate: "2025-05-25",
      completed: false,
      iconColor: "red",
    },
    {
      id: "r-6",
      title: "2019 Toyota Camry - 60+ Days",
      description: "Vehicle aging alert - floor plan interest",
      category: "vehicle",
      priority: "medium",
      dueDate: "2025-05-23",
      completed: false,
      iconColor: "orange",
    },
    {
      id: "r-7",
      title: "CPA Tax Document Request",
      description: "Submit Q1 P&L and expense reports",
      category: "accounting",
      priority: "medium",
      dueDate: "2025-05-28",
      completed: false,
      iconColor: "green",
    },
    {
      id: "r-8",
      title: "Custom Reminder - Vendor Contract",
      description: "Marketing vendor contract review",
      category: "custom",
      priority: "low",
      dueDate: "2025-05-30",
      completed: false,
      iconColor: "cyan",
    },
    {
      id: "r-9",
      title: "Smog Certificate - 2018 Ford F-150",
      description: "Overdue smog certification",
      category: "vehicle",
      priority: "high",
      dueDate: "2025-05-10",
      completed: false,
      iconColor: "red",
    },
    {
      id: "r-10",
      title: "Sales Tax Payment",
      description: "April 2025 CDTFA payment",
      category: "accounting",
      priority: "high",
      dueDate: "2025-05-05",
      completed: false,
      iconColor: "red",
    },
    {
      id: "r-11",
      title: "Employee Safety Training",
      description: "Annual OSHA compliance training",
      category: "employee",
      priority: "medium",
      dueDate: "2025-05-08",
      completed: false,
      iconColor: "orange",
    },
    {
      id: "r-12",
      title: "Deal RO-1008 Follow-up",
      description: "Pending funding documentation",
      category: "deal",
      priority: "medium",
      dueDate: "2025-05-12",
      completed: false,
      iconColor: "purple",
    },
    {
      id: "r-13",
      title: "Business License Renewal",
      description: "City dealer license renewal",
      category: "business",
      priority: "high",
      dueDate: "2025-05-15",
      completed: false,
      iconColor: "red",
    },
    {
      id: "r-14",
      title: "Vehicle Registration - 2021 BMW X3",
      description: "Registration transfer pending",
      category: "vehicle",
      priority: "low",
      dueDate: "2025-06-01",
      completed: false,
      iconColor: "blue",
    },
    {
      id: "r-15",
      title: "Monthly CPA Review",
      description: "Completed April review session",
      category: "accounting",
      priority: "low",
      dueDate: "2025-04-30",
      completed: true,
      iconColor: "green",
    },
    {
      id: "r-16",
      title: "Floor Plan Reconciliation",
      description: "Completed May reconciliation",
      category: "business",
      priority: "medium",
      dueDate: "2025-05-01",
      completed: true,
      iconColor: "green",
    },
    {
      id: "r-17",
      title: "Deal RO-1005 Closed",
      description: "All documents filed",
      category: "deal",
      priority: "low",
      dueDate: "2025-05-02",
      completed: true,
      iconColor: "green",
    },
    {
      id: "r-18",
      title: "Vehicle Detail - 2022 Chevy Silverado",
      description: "Reconditioning complete",
      category: "vehicle",
      priority: "low",
      dueDate: "2025-05-03",
      completed: true,
      iconColor: "green",
    },
    {
      id: "r-19",
      title: "Quarterly Tax Estimate",
      description: "Q2 estimated tax payment prep",
      category: "accounting",
      priority: "medium",
      dueDate: "2025-06-15",
      completed: false,
      iconColor: "blue",
    },
    {
      id: "r-20",
      title: "Employee Performance Review",
      description: "Q2 review for sales team",
      category: "employee",
      priority: "low",
      dueDate: "2025-06-10",
      completed: false,
      iconColor: "cyan",
    },
  ],

  categories: [
    { category: "vehicle", label: "Vehicle Reminders", count: 12, iconColor: "blue" },
    { category: "deal", label: "Deal Reminders", count: 9, iconColor: "purple" },
    { category: "accounting", label: "Accounting & CPA", count: 14, iconColor: "green" },
    { category: "employee", label: "Employee Reminders", count: 6, iconColor: "orange" },
    { category: "business", label: "Business Reminders", count: 7, iconColor: "blue" },
    { category: "custom", label: "Custom Reminders", count: 11, iconColor: "cyan" },
  ],

  upcomingPayments: [
    {
      id: "p-1",
      name: "Payroll",
      vendor: "Payroll",
      amount: 8250,
      dueDate: "2025-05-23",
      category: "Payroll",
      statusLabel: "Due in 3 days",
      statusTone: "orange",
    },
    {
      id: "p-2",
      name: "Sales Commissions",
      vendor: "Sales Commissions",
      amount: 4150,
      dueDate: "2025-05-25",
      category: "Commissions",
      statusLabel: "Due in 5 days",
      statusTone: "orange",
    },
    {
      id: "p-3",
      name: "Office Rent",
      vendor: "Office Rent",
      amount: 2500,
      dueDate: "2025-05-21",
      category: "Rent",
      statusLabel: "Due Tomorrow",
      statusTone: "yellow",
    },
    {
      id: "p-4",
      name: "CDTFA Payment",
      vendor: "CDTFA",
      amount: 6200,
      dueDate: "2025-05-28",
      category: "Tax",
      statusLabel: "Due in 8 days",
      statusTone: "orange",
    },
    {
      id: "p-5",
      name: "Dealer Insurance",
      vendor: "Dealer Insurance",
      amount: 3450,
      dueDate: "2025-05-26",
      category: "Insurance",
      statusLabel: "Due in 6 days",
      statusTone: "orange",
    },
  ],

  recurringPayments: [
    {
      id: "rp-1",
      vendor: "AT&T",
      category: "Internet",
      dueDate: "2025-06-01",
      amount: 189.99,
      frequency: "Monthly",
    },
    {
      id: "rp-2",
      vendor: "Dealer Insurance",
      category: "Insurance",
      dueDate: "2025-06-05",
      amount: 1150,
      frequency: "Monthly",
    },
    {
      id: "rp-3",
      vendor: "Google Ads",
      category: "Advertising",
      dueDate: "2025-06-01",
      amount: 2500,
      frequency: "Monthly",
    },
    {
      id: "rp-4",
      vendor: "QuickBooks",
      category: "Software",
      dueDate: "2025-06-10",
      amount: 75,
      frequency: "Monthly",
    },
    {
      id: "rp-5",
      vendor: "Utilities",
      category: "Utilities",
      dueDate: "2025-06-15",
      amount: 420,
      frequency: "Monthly",
    },
    {
      id: "rp-6",
      vendor: "Rent",
      category: "Rent",
      dueDate: "2025-06-01",
      amount: 2500,
      frequency: "Monthly",
    },
  ],

  calendarEvents: [
    {
      id: "ce-1",
      title: "CDTFA Filing",
      start: "2025-05-20",
      end: "2025-05-20",
      color: "bg-red-500/80",
      type: "compliance",
      dayIndex: 0,
      spanDays: 1,
    },
    {
      id: "ce-2",
      title: "Payroll Due",
      start: "2025-05-22",
      end: "2025-05-22",
      color: "bg-blue-500/80",
      type: "payment",
      dayIndex: 2,
      spanDays: 1,
    },
    {
      id: "ce-3",
      title: "Insurance Renewal",
      start: "2025-05-23",
      end: "2025-05-24",
      color: "bg-purple-500/80",
      type: "business",
      dayIndex: 3,
      spanDays: 2,
    },
    {
      id: "ce-4",
      title: "Sales Commissions",
      start: "2025-05-25",
      end: "2025-05-25",
      color: "bg-amber-500/80",
      type: "payment",
      dayIndex: 5,
      spanDays: 1,
    },
    {
      id: "ce-5",
      title: "Tax Review",
      start: "2025-05-21",
      end: "2025-05-21",
      color: "bg-emerald-500/80",
      type: "accounting",
      dayIndex: 1,
      spanDays: 1,
    },
  ],

  aiSuggestions: [
    { id: "sug-1", label: "What's due today?", icon: "clock" },
    { id: "sug-2", label: "Show me all overdue reminders", icon: "alert" },
    { id: "sug-3", label: "Which vehicles are over 60 days?", icon: "car" },
    { id: "sug-4", label: "What payments are due this week?", icon: "dollar" },
    { id: "sug-5", label: "Show all recurring payments", icon: "repeat" },
    { id: "sug-6", label: "What tax filings are due this month?", icon: "file" },
    { id: "sug-7", label: "What documents are missing in deal jackets?", icon: "folder" },
    {
      id: "sug-8",
      label: "How much cash do I need for upcoming obligations?",
      icon: "wallet",
    },
  ],
};
