import type { ReportsRemindersMock } from "./types";

export const REPORTS_REMINDERS_MOCK: ReportsRemindersMock = {
  kpis: [
    {
      icon: "dollar-sign",
      color: "green",
      label: "Total Revenue",
      value: "$512,450",
      delta: "... 16.3% vs last month",
      sparkColor: "#22c55e",
      sparkPoints:
        "0,38 25,32 50,28 75,26 100,22 125,20 150,16 175,14 200,12 220,8",
    },
    {
      icon: "pie-chart",
      color: "violet",
      label: "Gross Profit",
      value: "$98,420",
      delta: "... 18.3% vs last month",
      sparkColor: "#a855f7",
      sparkPoints:
        "0,40 25,34 50,30 75,26 100,24 125,18 150,16 175,12 200,10 220,6",
    },
    {
      icon: "bar-chart-3",
      color: "blue",
      label: "Net Profit",
      value: "$62,150",
      delta: "... 14.6% vs last month",
      sparkColor: "#3b82f6",
      sparkPoints:
        "0,36 25,32 50,28 75,24 100,22 125,18 150,16 175,12 200,10 220,8",
    },
    {
      icon: "car",
      color: "orange",
      label: "Vehicles Sold",
      value: "78",
      delta: "... 13.4% vs last month",
      sparkColor: "#f97316",
      sparkPoints:
        "0,40 25,36 50,32 75,28 100,26 125,22 150,18 175,14 200,12 220,10",
    },
    {
      icon: "users",
      color: "amber",
      label: "Vehicles Purchased",
      value: "42",
      delta: "... 8.7% vs last month",
      sparkColor: "#eab308",
      sparkPoints:
        "0,38 25,34 50,30 75,28 100,24 125,22 150,18 175,16 200,14 220,12",
    },
    {
      icon: "trending-down",
      color: "red",
      label: "Total Expenses",
      value: "$16,190",
      delta: "... 9.2% vs last month",
      sparkColor: "#ef4444",
      sparkPoints:
        "0,32 25,30 50,28 75,26 100,24 125,22 150,20 175,18 200,16 220,14",
    },
    {
      icon: "percent",
      color: "green",
      label: "Sales Tax Collected",
      value: "$8,425",
      delta: "... 7.1% vs last month",
      sparkColor: "#14b8a6",
      sparkPoints:
        "0,36 25,32 50,28 75,26 100,22 125,20 150,18 175,14 200,12 220,10",
    },
    {
      icon: "landmark",
      color: "green",
      label: "Payroll Paid",
      value: "$9,850",
      delta: "... 5.5% vs last month",
      sparkColor: "#4ade80",
      sparkPoints:
        "0,38 25,34 50,32 75,28 100,26 125,24 150,20 175,18 200,16 220,14",
    },
  ],
  reportSummary: [
    { label: "Total Revenue", value: "$512,450", tone: "positive" },
    { label: "Cost of Goods Sold", value: "$326,200", tone: "negative" },
    { label: "Gross Profit", value: "$186,250", tone: "positive" },
    { label: "Total Expenses", value: "$124,060", tone: "negative" },
    { label: "Net Profit", value: "$62,190", tone: "positive" },
    { label: "Net Profit Margin", value: "12.1%", tone: "positive" },
  ],
  salesPerformance: [
    {
      rank: 1,
      name: "Mike Thompson",
      carsSold: 18,
      grossProfit: "$28,760",
      commission: "$5,752",
      closingRatio: "28.6%",
    },
    {
      rank: 2,
      name: "Sarah Williams",
      carsSold: 16,
      grossProfit: "$25,840",
      commission: "$5,168",
      closingRatio: "25.4%",
    },
    {
      rank: 3,
      name: "Chris Allen",
      carsSold: 14,
      grossProfit: "$21,390",
      commission: "$4,278",
      closingRatio: "23.7%",
    },
    {
      rank: 4,
      name: "David Martinez",
      carsSold: 12,
      grossProfit: "$18,650",
      commission: "$3,730",
      closingRatio: "21.8%",
    },
    {
      rank: 5,
      name: "Emily Davis",
      carsSold: 10,
      grossProfit: "$15,780",
      commission: "$3,156",
      closingRatio: "20.0%",
    },
  ],
  expenseBars: [
    { label: "Vehicle Repairs", amount: 3250, percent: 20.1, color: "#ef4444" },
    { label: "Payroll", amount: 2950, percent: 18.2, color: "#3b82f6" },
    { label: "Rent", amount: 2100, percent: 13.0, color: "#22c55e" },
    { label: "Advertising", amount: 1850, percent: 11.4, color: "#a855f7" },
    { label: "Software", amount: 1250, percent: 7.7, color: "#f97316" },
    { label: "Utilities", amount: 850, percent: 5.3, color: "#06b6d4" },
    { label: "Miscellaneous", amount: 1900, percent: 12.3, color: "#6b7280" },
  ],
  inventory: {
    totalVehicles: 85,
    avgDaysInStock: 42,
    inventoryValue: "$675,230",
    estProfitInInventory: "$145,680",
    breakdown: [
      {
        id: "under-30",
        label: "Under 30 Days",
        color: "#22c55e",
        count: 28,
        percent: 32.9,
      },
      {
        id: "30-60",
        label: "30 - 60 Days",
        color: "#3b82f6",
        count: 22,
        percent: 25.9,
      },
      {
        id: "60-90",
        label: "60 - 90 Days",
        color: "#f59e0b",
        count: 18,
        percent: 21.2,
      },
      {
        id: "90-plus",
        label: "90+ Days",
        color: "#6b7280",
        count: 17,
        percent: 20.0,
      },
    ],
  },
  profitLossSummary: [
    { label: "Total Revenue", value: "$512,450", tone: "positive" },
    { label: "Cost of Goods Sold", value: "$336,200", tone: "negative" },
    { label: "Gross Profit", value: "$186,250", tone: "positive" },
    { label: "Operating Expenses", value: "$124,060", tone: "negative" },
    { label: "Net Profit", value: "$62,190", tone: "positive" },
    { label: "Net Profit Margin", value: "12.1%", tone: "positive" },
  ],
  payroll: [
    { label: "Total Payroll", value: "$9,650" },
    { label: "Employees Paid", value: "8" },
    { label: "Pay Periods", value: "2" },
  ],
  commissions: [
    { label: "Total Commissions", value: "$21,080" },
    { label: "Pending Commissions", value: "$6,320" },
    { label: "Paid Commissions", value: "$14,760" },
  ],
  dealJacketStatus: [
    { label: "Completed", count: 58, percent: "72.5%", tone: "green" },
    { label: "In Progress", count: 16, percent: "20.0%", tone: "blue" },
    { label: "Missing Docs", count: 6, percent: "7.5%", tone: "orange" },
    { label: "Funded", count: 42, percent: "52.5%", tone: "emerald" },
  ],
  auditReadiness: {
    percent: 92,
    subtitle: "Audit Readiness Score",
    items: [
      { label: "Receipts Uploaded", done: true },
      { label: "Deal Jackets Complete", done: true },
      { label: "Payroll Updated", done: true },
      { label: "Sales Tax Filed", done: true },
      { label: "Missing Documents", done: false, badge: "6" },
    ],
  },
  customReportFields: [
    { id: "report_type", label: "Report Type", value: "Vehicle Sales" },
    { id: "date_range", label: "Date Range", value: "This Month" },
    { id: "sales_rep", label: "Sales Rep", value: "All Sales Reps" },
    { id: "vehicle_make", label: "Vehicle Make", value: "Toyota" },
    { id: "min_profit", label: "Min. Profit", value: "$3,000+" },
  ],
  topReminders: [
    {
      id: "tr-1",
      title: "Deal Jackets Missing Documents",
      statusLabel: "Overdue",
      statusTone: "red",
      iconTone: "amber",
    },
    {
      id: "tr-2",
      title: "CDTFA Filing Due",
      statusLabel: "Due Today",
      statusTone: "orange",
      iconTone: "red",
    },
    {
      id: "tr-3",
      title: "Payroll for 08/15/2025",
      statusLabel: "Due Today",
      statusTone: "orange",
      iconTone: "emerald",
    },
    {
      id: "tr-4",
      title: "3 Registrations Expiring Soon",
      statusLabel: "Due This Week",
      statusTone: "blue",
      iconTone: "lime",
    },
    {
      id: "tr-5",
      title: "Smog Inspections Due",
      statusLabel: "Due This Week",
      statusTone: "blue",
      iconTone: "blue",
    },
  ],
  stickyNotes: [
    {
      id: "n-1",
      color: "#fef08a",
      text: "Follow up with CPA on Q1 filings before month end.",
      date: "May 18, 2025",
      author: "John Dealer",
    },
    {
      id: "n-2",
      color: "#bbf7d0",
      text: "Review floor plan interest on 60+ day units.",
      date: "May 17, 2025",
      author: "Sarah Williams",
    },
    {
      id: "n-3",
      color: "#bfdbfe",
      text: "Schedule marketing vendor contract review.",
      date: "May 16, 2025",
      author: "Mike Thompson",
    },
    {
      id: "n-4",
      color: "#fbcfe8",
      text: "Confirm CDTFA payment posted for April filing.",
      date: "May 15, 2025",
      author: "John Dealer",
    },
  ],
  aiSuggestions: [
    {
      id: "ra-1",
      label: "Show my most profitable vehicles this month",
      icon: "car",
    },
    {
      id: "ra-2",
      label: "Summarize overdue reminders",
      icon: "alert",
    },
    {
      id: "ra-3",
      label: "Compare gross profit vs last month",
      icon: "chart",
    },
    {
      id: "ra-4",
      label: "Which sales rep closed the most deals?",
      icon: "dollar",
    },
    {
      id: "ra-5",
      label: "What expenses increased the most?",
      icon: "file",
    },
    {
      id: "ra-6",
      label: "Show inventory aging over 60 days",
      icon: "clock",
    },
  ],
};
