"use client";

import { Car, CheckCircle, Package, ShieldCheck, ShoppingBag } from "lucide-react";
import { Card } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import type { PlInsight, ProfitLossMeta } from "@/lib/profit-loss/types";
import { formatDateTime } from "@/lib/expenses/types";

const INSIGHT_ICONS = {
  check: { Icon: CheckCircle, bg: "bg-emerald-500/15 text-emerald-400" },
  car: { Icon: Car, bg: "bg-blue-500/15 text-blue-400" },
  package: { Icon: Package, bg: "bg-orange-500/15 text-orange-400" },
  bag: { Icon: ShoppingBag, bg: "bg-purple-500/15 text-purple-400" },
};

type Props = {
  insights: PlInsight[];
  meta: ProfitLossMeta;
  periodEnd: string;
};

export default function ProfitLossSummary({ insights, meta, periodEnd }: Props) {
  const details = [
    { label: "Report Type", value: meta.reportType },
    { label: "Generated On", value: formatDateTime(meta.generatedAt) },
    { label: "Generated By", value: meta.generatedBy },
    { label: "Currency", value: meta.currency },
    { label: "Data Source", value: meta.dataSource },
    { label: "Basis", value: meta.basis === "cash" ? "Cash Basis" : "Accrual Basis" },
  ];

  const endDate = formatDateTime(`${periodEnd}T11:45:00`);

  return (
    <div className="space-y-3.5">
      <Card className="rounded-sm border border-slate-700 bg-card p-3.5 shadow-none">
        <h3 className="mb-3 text-[11px] font-bold uppercase tracking-[0.14em] text-slate-500">
          Summary Insights
        </h3>
        <ul className="space-y-3">
          {insights.map((insight) => {
            const { Icon, bg } = INSIGHT_ICONS[insight.icon];
            return (
              <li key={insight.id} className="flex gap-2.5">
                <div
                  className={cn(
                    "mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-full",
                    bg,
                  )}
                >
                  <Icon className="h-3.5 w-3.5" />
                </div>
                <p className="text-[11.5px] leading-relaxed text-slate-300">
                  {insight.text}
                </p>
              </li>
            );
          })}
        </ul>
      </Card>

      <Card className="rounded-sm border border-slate-700 bg-card p-3.5 shadow-none">
        <h3 className="mb-3 text-[11px] font-bold uppercase tracking-[0.14em] text-slate-500">
          Report Details
        </h3>
        <dl className="space-y-2">
          {details.map(({ label, value }) => (
            <div key={label} className="flex justify-between gap-4 text-[11px]">
              <dt className="text-slate-500">{label}</dt>
              <dd className="text-right font-medium text-slate-200">{value}</dd>
            </div>
          ))}
        </dl>
      </Card>

      <div className="flex items-start gap-2 px-0.5">
        <ShieldCheck className="mt-0.5 size-7 shrink-0 text-emerald-400" />
        <p className="text-[13px] leading-relaxed text-slate-500">
          This report is auto-generated and includes all posted transactions up to{" "}
          {endDate}.
        </p>
      </div>
    </div>
  );
}
